### ISSUE TITLE
There are no commands defined in the "assetic" namespace.

### ISSUE THREAD

**Issue by andreclemente** [sanpii/assetic-bundle#5]
Hi, i've been working with sanpii/assetic-bundle on symfony 4.3 for some time now.

Today, after running `composer update` when I tried to run `bin/console assetic:dump --env=dev` this was the output:
```
There are no commands defined in the "assetic" namespace.  
                                                             
  Did you mean this?                                         
      assets  
```
Any thoughts about this?

**Comment by andreclemente** [comment]
I was able to make it work again using [(https://github.com/StudioMaX/assetic-bundle)]

**Comment by andreclemente** [comment]
I was able to make it work again using https://github.com/StudioMaX/assetic-bundle

**Comment by StudioMaX** [comment]
@andreclemente this is just a fork of v2.9.0. It's better to fix composer require to someting like this as a workaround
```
"sanpi/assetic-bundle": "^2.9,!=2.10.0",
```

**Comment by fuerst-ede** [comment]
This problem seems to be introduced by the force push from 95b2f79 to fa32959.
Since the 95b2f79 is not reachable anymore, I can not compare it to the current one, but I can say that 95b2f79 still had assetic:dump registered and fa32959 does not.

**Comment by StudioMaX** [comment]
Haha, I recently did not understand why @sanpii added commits to my PR https://github.com/sanpii/assetic-bundle/pull/4/commits

**Comment by dontub** [comment]
In 95b2f79 the commands are registered by this config: https://github.com/sanpii/assetic-bundle/blob/95b2f79b5d38af46b5dc26a7ec679176c7f80b79/Resources/config/commands.xml

Until this is fixed I'll continue to use
```
"sanpi/assetic-bundle": "dev-master#95b2f79"
```

**Comment by StudioMaX** [comment]
We should move out from Assetic. This bundle requires the `symfony/templating` component, which was deprecated in Symfony 4.3 and will be removed since Symfony 5.0 (see https://symfony.com/blog/new-in-symfony-4-3-deprecated-the-templating-component-integration).
This Assetic bundle is tied on that component and will require a lot of refactoring, which most likely no one will do. Now this bundle will throw deprecations in Symfony, which cannot be hidden.

**Comment by blazarecki** [comment]
@dontub you also need to use sanpi/assetic 1.5.0 and not 1.6.0 because of this issue:
`Declaration of Symfony\Bundle\AsseticBundle\Twig\AsseticTokenParser::createNode(Assetic\Asset\AssetInterface $asset, Twig_NodeInterface $body, array $inputs, array $filters, $name, array $attributes = Array, $lineno = 0, $tag = NULL) should be compatible with Assetic\Extension\Twig\AsseticTokenParser::createNode(Assetic\Asset\AssetInterface $asset, Twig\NodeInterface $body, array $inputs, array $filters, $name, array $attributes = Array, $lineno = 0, $tag = NULL)
`

**Comment by sanpii** [comment]
Fixed.
